### ISSUE TITLE
train1.py 실행시 오류

### ISSUE THREAD

**Issue by piaasol** [chldkato/Tacotron-Korean#1]
kss 샘플데이터로 실행시 아래와 같은 오류 발생합니다.~
(tensorflow==1.15.4)

하기 batch size 줄여서 실행(테스트데이터사이즈고려)
Traceback (most recent call last):
  File "/Tacotron-Korean/models/datafeeder.py", line 56, in run
    idx_list = np.random.choice(len(mel_list), batch_size ** 2, replace=False)
  File "mtrand.pyx", line 948, in numpy.random.mtrand.RandomState.choice
ValueError: Cannot take a larger sample than population when 'replace=False'
후,
tensorflow.python.framework.errors_impl.InvalidArgumentError: Incompatible shapes: [32,545,80] vs. [32,540,80]

**Comment by chldkato** [comment]
해당 에러는 choice(a, b)에서 b가 a보다 크기 때문에 발생합니다
len(mel_list)가 제대로 인식되지 않는거 같습니다
처음부터 다시 실행해봤는데 코드를 수정하지 않았다면 정상적으로 진행됩니다

**Comment by piaasol** [comment]
아 빠른 답변감사합니다. 다시진행해보겠습니다.
